name: Sync Fork

on:
  schedule:
    - cron: '0 12 * * 5' # at 12:00 every Friday
  workflow_dispatch: # on button click

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          base: main
          head: l2d
